### ISSUE TITLE
Show the win animation without setting all cards on top

### ISSUE THREAD

**Issue by thiago-s-medeiros** [doofy-dev/flipper_solitaire#1]
My idea is that when all the cards are already revealed and are in the correct order, the game should automatically place them at the top and show the victory animation. (Maybe need a toggle on/off?)

Something like windows solitaire does

**Comment by teeebor** [comment]
I'm thinking that when you revealed all the cards somewhere the screen it should show a message like "Hold * to solve" then there is not need for the togggle.
What do you think?

**Comment by thiago-s-medeiros** [comment]
Yeah! This is a nice way to solve this request 🤘🏻 

Yes! if you don't mind, I think maybe something like [this](https://www.youtube.com/shorts/6NIzRulucuo) from 0:00 to 0:02.

**Comment by teeebor** [comment]
Then this is gonna be the next update :D

**Comment by doofy-dev** [comment]
Soon™
Finally had time to continue working on the game, detection for it this request is implemented.

![solve_WIP](https://github.com/doofy-dev/flipper_solitaire/assets/5022688/4b912f00-e7d2-439f-9d48-89d148a71960)

**Comment by doofy-dev** [comment]
Sorry for the long hiatus, released the new version with this feature included.
